# Generated by Django 2.0.6 on 2019-10-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUserApp', '0002_usersignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='userConfirmationlink',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='userOtp',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='userOtptime',
            field=models.CharField(default='', max_length=200),
        ),
    ]
