# Generated by Django 2.0.6 on 2019-10-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUserApp', '0003_auto_20191004_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='isQueue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='userToken',
            field=models.CharField(default='', max_length=200),
        ),
    ]
