# Generated by Django 2.0.6 on 2019-11-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUserApp', '0006_usersignup_userimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('userEmail', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('subject', models.CharField(default='', max_length=500)),
                ('contactDate', models.CharField(default='', max_length=30)),
                ('textArea', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
