# Generated by Django 2.0.6 on 2019-11-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyUserApp', '0007_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
