# Generated by Django 2.0.6 on 2019-10-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0002_loginrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='depttName',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
