# Generated by Django 2.0.6 on 2019-11-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='isDiagonal',
            field=models.BooleanField(default=False),
        ),
    ]
