# Generated by Django 2.0.6 on 2019-10-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='userDepartment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='userPost',
            field=models.CharField(default='', max_length=200),
        ),
    ]
