# Generated by Django 2.0.6 on 2019-11-12 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0002_appointment_isdiagonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPrescription',
            fields=[
                ('PrescriptionId', models.AutoField(primary_key=True, serialize=False)),
                ('Medicine', models.CharField(default='', max_length=500)),
                ('Prescription', models.CharField(default='', max_length=500)),
                ('Test', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('PatientId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='staffapp.Appointment')),
            ],
        ),
    ]
