# Generated by Django 2.0.6 on 2019-10-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0002_auto_20191017_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='userDepartment',
        ),
    ]
