# Generated by Django 2.0.6 on 2019-11-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0004_auto_20191023_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('userEmail', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('userName', models.CharField(default='', max_length=200)),
                ('userMobile', models.CharField(default='', max_length=200)),
                ('userAddress', models.CharField(default='', max_length=500)),
                ('userCity', models.CharField(default='', max_length=10)),
                ('userState', models.CharField(default='', max_length=200)),
                ('userDisease', models.CharField(default='', max_length=200)),
                ('department', models.CharField(default='', max_length=200)),
                ('doctor', models.CharField(default='', max_length=200)),
                ('appointmentDate', models.CharField(default='', max_length=200)),
                ('isActive', models.BooleanField(default=True)),
                ('isQueue', models.BooleanField(default=False)),
            ],
        ),
    ]
