# Generated by Django 2.0.6 on 2019-11-06 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0005_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmentDate',
            new_name='AppointmentDate',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='department',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='Doctor',
        ),
    ]
