# Generated by Django 2.0.6 on 2019-11-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0006_auto_20191106_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='userAge',
            field=models.CharField(default='', max_length=10),
        ),
    ]
