# Generated by Django 2.0.6 on 2019-11-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0007_appointment_userage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Doctor',
            new_name='DoctorName',
        ),
    ]
