# Generated by Django 2.0.6 on 2019-11-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0008_auto_20191106_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='userAddress',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='userAge',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='userCity',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='userDisease',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='userMobile',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='userState',
        ),
        migrations.AddField(
            model_name='staff',
            name='isBooked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='userCity',
            field=models.CharField(default='', max_length=200),
        ),
    ]
