# Generated by Django 2.0.6 on 2019-11-11 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0009_auto_20191107_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='DoctorName',
        ),
        migrations.AddField(
            model_name='appointment',
            name='DoctorEmail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='staffapp.Staff'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerapp.Department'),
        ),
    ]
